### ISSUE TITLE
Add Class Reference

### ISSUE THREAD

**Issue by CakeVR** [dialogic-godot/documentation#10]
Adding a class reference, like Godot Docs have, to this documentation would be very useful.
It will help to always scroll through the API for each released version of Dialogic.
Users can find all methods, properties, signals, and learn from the documented code.

For reference: https://docs.godotengine.org/en/4.0/classes/index.html

**Comment by DanielOaks** [comment]
[https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html](The CLI page) describes the `--doctool`, `--no-docbase`, and `--gdscript-docs` flags which could potentially be used to export data from the gdscript.

I think that may export XML so might need to toss it through a conversion script, but if we can autogenerate the class refs from the code comments that'd be nice.

**Comment by CakeVR** [comment]
The class reference has been added with #46.

The next step is the evaluation of #39.
