### ISSUE TITLE
Fix deadlinks on `README.md`

### ISSUE THREAD

**Issue by CakeVR** [dialogic-godot/documentation#18]
All hyperlinks on the `README.md` are incorrect and lead nowhere.

**Comment by Jowan-Spooner** [comment]
The dumb thing is though, that they work on the live page, just not on github. Maybe we should have a separate home-page and github readme page...

**Comment by Jowan-Spooner** [comment]
I think this is irrelevant now that readme and main page are different

**Comment by CakeVR** [comment]
You are right!
