### ISSUE TITLE
Improve Page sorting in the Sidebar

### ISSUE THREAD

**Issue by Jowan-Spooner** [dialogic-godot/documentation#3]
Not sure how this is best implemented, but I feel the sorting is really arbitrary right now. We might want to have sections for step by step guides (like Getting Started) and info pages.

**Comment by coppolaemilio** [comment]
Yes! the current sidebar is random actually. 
What sections should we have?

**Comment by Jowan-Spooner** [comment]
It's a bit tricky as (right now) we have a couple of pages which don't perfectly fit one of these sections.
But looking at the godot docs I'd say the ones we could need would be:

- About
- Guides/Tutorials
- Manual/Documentation/Information
- FAQ
- If we manage to automate it: Class Reference (especially for autogenerated reference of Subsystems & Events)
