### ISSUE TITLE
Add Links to Node Class Reference Index

### ISSUE THREAD

**Issue by Aronthata** [dialogic-godot/documentation#49]
could you make pages for the nodes, defining all the variables and callables? similar to the godot documentation?

**Comment by CakeVR** [comment]
Do you mean this: https://docs.dialogic.pro/class_index.html?

**Comment by Aronthata** [comment]
correct, however can you attach a link to those nodes in here so its more readily available?
https://docs.dialogic.pro/dialogic-nodes.html

**Comment by CakeVR** [comment]
> correct, however can you attach a link to those nodes in here so its more readily available? https://docs.dialogic.pro/dialogic-nodes.html

Good idea!
I have added links to the [Node Class Reference Index](node_class_index.md).
