### ISSUE TITLE
Not Able to Run or Play Games After Export 

### ISSUE THREAD

**Issue by vikram3** [dialogic-godot/documentation#50]
![image](https://github.com/dialogic-godot/documentation/assets/28431707/68a19210-91be-401b-aa5b-12c55d8bf4a2)

**Comment by CakeVR** [comment]
Hello, you opened an issue at the repository for documentation, please open an issue or thread over at https://github.com/dialogic-godot/dialogic.

Also ensure to include your Godot and Dialogic version. Your error may stem from the wrong Godot version. Dialogic 2's latest release (Alpha 13 and the latest commit), both require Godot 4.2.

If you need further help, please refer to the aforementioned link, thanks!
